name: Deploy Jekyll Site to GitHub Pages

on:
  push:
    branches:
      - gh-pages # Change this to your default branch if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.1  # Match your Ruby version
          bundler-cache: true

      # Install dependencies
      - name: Install dependencies
        run: |
          bundle install

      # Build the Jekyll site
      - name: Build site
        run: |
          bundle exec jekyll build --destination _site

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
